[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # faster linking
  "-C", "link-arg=-fuse-ld=mold",
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]
